### ISSUE TITLE
Hitting Something North of Sifnos and Sinking

### ISSUE THREAD

**Issue by jesawyers** [nitroman123/Ship-Simulator-Realistic#71]
v0.8.3.3 test branch.  I'm hitting something and sinking a little north and west of Sifnos. I will try to get a map screen shot and it has happened several times.  I've been trying to sail from Port of Sifnos to Port of Andros.

**Comment by nitroman123** [comment]
yes i found the problem it was reported from your fellow tester , i fixed it hopefully

**Comment by jesawyers** [comment]
This is still an issue.  I also hit something twice exiting the port but did not sink.

**Comment by jesawyers** [comment]
Problem fixed.  Issue can be closed.
